### ISSUE TITLE
Increase size fonts

### ISSUE THREAD

**Issue by chaimgross** [zvikarp/daf_counter#15]
I think size fonts throughout can probably be increased by a few. Definitely the mesechta names

**Comment by zvikarp** [comment]
ok, also the font itsef isnt very readable, do you think we should switch it? 

the font is from [google fonts](https://fonts.google.com/?subset=hebrew) and its called Frank Ruhl Libre.

**Comment by chaimgross** [comment]
Yes, I also thought wasn't readable

**Comment by zvikarp** [comment]
what do you think of the "alef" font? https://fonts.google.com/specimen/Alef

**Comment by zvikarp** [comment]
![Screenshot_20200225-102133](https://user-images.githubusercontent.com/13397207/75228350-aa3dd780-57b8-11ea-9046-e2a67c04b219.png)

**Comment by chaimgross** [comment]
much better

**Comment by chaimgross** [comment]
https://fonts.google.com/specimen/Varela+Round 
this also looks fine

**Comment by chaimgross** [comment]
but the one you sent looks great
